#!/bin/sh
# Publish `main` to the production repository, without the internal docs.
#
# Production is a build mirror: GitHub Actions checks it out and builds the
# site there, so it needs the source — but not IDLC.md, PROJECT-LOG.md and the
# rest, which are working notes for the developer and the agentic flow. Only
# README.md is kept.
#
# It also must not carry a workflow that writes to the repository it runs in.
# See MIRROR_ONLY_WORKFLOWS below.
#
# The stripping cannot be done with .gitignore (the files are already tracked)
# or by deleting them in the production repo (the next push would restore
# them). So each deploy rewrites a throwaway branch and force-pushes it.
# Production's history is therefore a deployment artefact, not a source of
# truth — `origin` remains that. Nobody should commit directly to production.
#
# Usage:  sh scripts/deploy-prod.sh
set -eu

REMOTE=prod
BRANCH=prod-deploy

# Refuse to publish a tree that does not match what has been reviewed.
if [ -n "$(git status --porcelain)" ]; then
  echo "✗ Working tree is not clean. Commit or stash first." >&2
  exit 1
fi

git fetch -q origin
if [ "$(git rev-parse main)" != "$(git rev-parse origin/main)" ]; then
  echo "✗ main and origin/main differ. Push or pull before deploying." >&2
  exit 1
fi

# Every tracked .md except any README.md.
DOCS=$(git ls-files '*.md' | grep -v '\(^\|/\)README\.md$' || true)

# Workflows that must not run in a mirror.
#
# `rankone.yml` commits content/rankone.json to whichever repository it runs in.
# In production that is broken twice over. The commit is made with GITHUB_TOKEN,
# and by GitHub's recursion guard a GITHUB_TOKEN push triggers no other
# workflow — so deploy.yml never fires and the site is never rebuilt with the
# data it just fetched. And the next deploy force-pushes over the commit anyway,
# because this file rewrites production's history wholesale.
#
# It shipped here for weeks. Production ran the scraper three times a day, every
# run green in its Actions tab, and it rebuilt the site exactly zero times: on
# 2026-09-07 it fetched a real fixture change at 04:12 UTC and the page went on
# showing the previous afternoon. Green ticks for work that could not possibly
# have an effect is the worst shape a bug can take.
#
# The sync belongs in the source repository, which is where it lives and where
# its own header explains why. See PROJECT-DOCUMENTATION, "Keeping the schedule
# in sync".
MIRROR_ONLY_WORKFLOWS=$(git ls-files '.github/workflows/rankone.yml')

STRIP=$(printf '%s\n%s\n' "$DOCS" "$MIRROR_ONLY_WORKFLOWS" | grep -v '^$' || true)

echo "Stripping from the production tree:"
if [ -z "$STRIP" ]; then
  echo "  (none)"
else
  echo "$STRIP" | sed 's/^/  /'
fi

# Built entirely in a temporary index with plumbing: no checkout, no branch
# switch, and the working tree is never touched. An earlier version checked out
# a branch and ran `git rm --cached`, which untracks the files — and switching
# back then refuses to overwrite what are now untracked files, stranding the
# repo on the deploy branch.
# The template must carry its own XXXXXX. BSD mktemp treats `-t foo` as a
# prefix and invents the suffix; GNU mktemp rejects it outright with "too few
# X's in template", so `mktemp -t ko-prod-index` worked for two months of
# deploys from a Mac and failed the first time CI ran this on Ubuntu.
TMP_INDEX=$(mktemp "${TMPDIR:-/tmp}/ko-prod-index.XXXXXX")
trap 'rm -f "$TMP_INDEX"' EXIT

GIT_INDEX_FILE="$TMP_INDEX" git read-tree main

if [ -n "$STRIP" ]; then
  echo "$STRIP" | while IFS= read -r path; do
    [ -n "$path" ] && GIT_INDEX_FILE="$TMP_INDEX" git update-index --force-remove "$path"
  done
fi

TREE=$(GIT_INDEX_FILE="$TMP_INDEX" git write-tree)

# Assert it, rather than trust it. The `while` loop above runs in a subshell, so
# a failure inside it cannot stop this script; and a workflow that reaches
# production announces itself only as green runs that change nothing, which is
# how the last one survived weeks of deploys.
STRIP_LIST=$(mktemp "${TMPDIR:-/tmp}/ko-prod-strip.XXXXXX")
trap 'rm -f "$TMP_INDEX" "$STRIP_LIST"' EXIT
printf '%s\n' "$STRIP" > "$STRIP_LIST"
LEAKED=$(git ls-tree -r --name-only "$TREE" | grep -xF -f "$STRIP_LIST" || true)
if [ -n "$LEAKED" ]; then
  echo "✗ These should have been stripped and are still in the production tree:" >&2
  echo "$LEAKED" | sed 's/^/  /' >&2
  exit 1
fi

COMMIT=$(git commit-tree "$TREE" -p main -m "Deploy: strip internal docs and mirror-only workflows

Working notes for the developer and the agentic flow; not part of the
site and not wanted in the production mirror. README.md is kept.

Also stripped: .github/workflows/rankone.yml. It commits to the
repository it runs in, and a commit made with GITHUB_TOKEN triggers no
other workflow — so running it here fetches data that never reaches a
build, and the next deploy force-pushes over it regardless.

Generated by scripts/deploy-prod.sh — do not commit directly here.")

git push -q --force "$REMOTE" "$COMMIT":main
# Keep a local ref so the deployed commit is inspectable afterwards.
git update-ref "refs/heads/$BRANCH" "$COMMIT"

echo "✓ Pushed $(git rev-parse --short main) to $REMOTE/main, stripped."
echo "  GitHub Actions will build and deploy; watch the Actions tab."
