#!/bin/sh
# Publish `main` to the production repository, without the internal docs.
#
# Production is a build mirror: GitHub Actions checks it out and builds the
# site there, so it needs the source — but not IDLC.md, PROJECT-LOG.md and the
# rest, which are working notes for the developer and the agentic flow. Only
# README.md is kept.
#
# The stripping cannot be done with .gitignore (the files are already tracked)
# or by deleting them in the production repo (the next push would restore
# them). So each deploy rewrites a throwaway branch and force-pushes it.
# Production's history is therefore a deployment artefact, not a source of
# truth — `origin` remains that. Nobody should commit directly to production.
#
# Usage:  sh scripts/deploy-prod.sh
set -eu

REMOTE=prod
BRANCH=prod-deploy

# Refuse to publish a tree that does not match what has been reviewed.
if [ -n "$(git status --porcelain)" ]; then
  echo "✗ Working tree is not clean. Commit or stash first." >&2
  exit 1
fi

git fetch -q origin
if [ "$(git rev-parse main)" != "$(git rev-parse origin/main)" ]; then
  echo "✗ main and origin/main differ. Push or pull before deploying." >&2
  exit 1
fi

# Every tracked .md except any README.md.
DOCS=$(git ls-files '*.md' | grep -v '\(^\|/\)README\.md$' || true)

echo "Stripping from the production tree:"
if [ -z "$DOCS" ]; then
  echo "  (none)"
else
  echo "$DOCS" | sed 's/^/  /'
fi

# Built entirely in a temporary index with plumbing: no checkout, no branch
# switch, and the working tree is never touched. An earlier version checked out
# a branch and ran `git rm --cached`, which untracks the files — and switching
# back then refuses to overwrite what are now untracked files, stranding the
# repo on the deploy branch.
TMP_INDEX=$(mktemp -t ko-prod-index)
trap 'rm -f "$TMP_INDEX"' EXIT

GIT_INDEX_FILE="$TMP_INDEX" git read-tree main

if [ -n "$DOCS" ]; then
  echo "$DOCS" | while IFS= read -r doc; do
    [ -n "$doc" ] && GIT_INDEX_FILE="$TMP_INDEX" git update-index --force-remove "$doc"
  done
fi

TREE=$(GIT_INDEX_FILE="$TMP_INDEX" git write-tree)
COMMIT=$(git commit-tree "$TREE" -p main -m "Deploy: strip internal docs

Working notes for the developer and the agentic flow; not part of the
site and not wanted in the production mirror. README.md is kept.

Generated by scripts/deploy-prod.sh — do not commit directly here.")

git push -q --force "$REMOTE" "$COMMIT":main
# Keep a local ref so the deployed commit is inspectable afterwards.
git update-ref "refs/heads/$BRANCH" "$COMMIT"

echo "✓ Pushed $(git rev-parse --short main) to $REMOTE/main without the internal docs."
echo "  GitHub Actions will build and deploy; watch the Actions tab."
