// Content source: content/rankone.json — GENERATED by scripts/fetch-rankone.mjs
// on a schedule (.github/workflows/rankone.yml). Not a CMS collection: /admin
// never shows it and validate-content.mts ignores it, the same arrangement as
// content/gallery.json. Editing it by hand is pointless — the next run wins.
import rankoneJson from "@content/rankone.json";
import type { Match, MatchTimes } from "@/data/matches";

export type RankOneGame = {
  /** YYYY-MM-DD, taken from the feed's hidden field rather than its "Aug 7" label. */
  date: string;
  time: string;
  home: boolean;
  opponent: string;
  venue: string;
  address: string;
  map: string;
  note: string;
  status: string;
  result: string;
};

export type RankOneLevel = {
  label: string;
  teamId: string;
  url: string;
  games: RankOneGame[];
};

type RankOneFeed = {
  source: string;
  /**
   * ISO instant of the **last run**, changed or not. This is what the schedule
   * page shows: "checked at 6am and nothing had moved" is the reassurance a
   * parent wants the night before a match, and a date that only advances when
   * something changes cannot say it.
   */
  checkedAt: string;
  /** YYYY-MM-DD of the last run where the games themselves differed. */
  changedAt: string;
  levels: Record<string, RankOneLevel>;
};

export const rankone = rankoneJson as RankOneFeed;

/** ISO instant of the last sync run. */
export const checkedAt = rankone.checkedAt;
/** YYYY-MM-DD the schedule data last actually moved. */
export const changedAt = rankone.changedAt;
/** How many fixtures the feeds carry, across all four levels. */
export const gameCount = levelsOfFeed(rankone).reduce((n, l) => n + l.games.length, 0);

function levelsOfFeed(feed: RankOneFeed) {
  return Object.values(feed.levels);
}

export type Venue = { venue: string; address: string; map: string };

/** Every game any level plays between two dates, inclusive. */
function gamesBetween(from: string, to: string): RankOneGame[] {
  return levelsOfFeed(rankone).flatMap((level) =>
    level.games.filter((game) => game.date >= from && game.date <= to),
  );
}

/**
 * Words that carry no identity. "Oak Ridge" and "Oak Ridge HS" are the same
 * place; "Klein Oak High School" and "Klein Oak Competition Gym" are too.
 */
const NOISE = new Set([
  "hs", "h", "high", "school", "stadium", "gym", "gymnasium", "competition",
  "auxiliary", "the", "at", "campus", "center", "centre",
]);

const significant = (name: string) =>
  name
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, " ")
    .split(/\s+/)
    .filter((word) => word && !NOISE.has(word));

/** Is the curated location name recognisable in the feed's venue name? */
function namesAgree(location: string, venue: string): boolean {
  const wanted = significant(location);
  if (wanted.length === 0) return false;
  const have = new Set(significant(venue));
  // Every significant word must appear. Overlap alone is not enough: "Klein
  // Oak" and "Klein Forest" share a word and are twenty minutes apart.
  return wanted.every((word) => have.has(word));
}

/**
 * Where a fixture is played, according to whichever levels' calendars list it.
 *
 * The feed is matched on **date**, not on opponent — the feed writes "Lake Creek
 * High School LCHS VB V" where the site says "Lake Creek", and a tournament is
 * one curated row against a dozen feed rows, so opponent matching is the
 * fragile option. But date alone is not enough either, and the failure is not
 * theoretical: on 2026-08-08 the site carries both an Oak Ridge scrimmage and
 * team bonding at Bowlero, while Rank One lists only the scrimmage. Matching on
 * date put "Oak Ridge HS" under Bowlero — a wrong address on a page parents use
 * to decide where to drive.
 *
 * So the curated location has to agree with the feed's venue name before a
 * venue is shown at all, and when the curated location is the generic "Home" or
 * "Away" there is nothing to agree with, so the date must resolve to exactly one
 * venue. Anything ambiguous renders nothing, which is the correct output: the
 * row still shows Home/Away, just without an address the site cannot stand
 * behind.
 */
export function venueFor(match: Pick<Match, "startDate" | "endDate" | "location">): Venue | undefined {
  if (!match.startDate) return undefined;

  const games = gamesBetween(match.startDate, match.endDate ?? match.startDate).filter(
    (game) => game.venue && game.map,
  );
  if (games.length === 0) return undefined;

  // Grouped by **address**, not by venue name. A home date lists "Klein Oak
  // Competition Gym" for varsity and "Klein Oak Auxiliary Gym" for freshmen —
  // two names, two rooms, one building at 22603 Northcrest Drive. Counting
  // names would call that ambiguous and show nothing on every home fixture.
  const byAddress = new Map<string, { venues: Map<string, { venue: Venue; n: number }>; n: number }>();
  for (const game of games) {
    const group = byAddress.get(game.address) ?? { venues: new Map(), n: 0 };
    const entry = group.venues.get(game.venue);
    if (entry) entry.n += 1;
    else
      group.venues.set(game.venue, {
        venue: { venue: game.venue, address: game.address, map: game.map },
        n: 1,
      });
    group.n += 1;
    byAddress.set(game.address, group);
  }

  /** Most-listed venue name at one address; name breaks a tie so builds are stable. */
  const pick = (group: { venues: Map<string, { venue: Venue; n: number }> }) =>
    [...group.venues.values()].sort(
      (x, y) => y.n - x.n || x.venue.venue.localeCompare(y.venue.venue),
    )[0].venue;

  const location = match.location?.trim() ?? "";

  // "Home", "Away" and a blank say nothing a venue name can be checked against,
  // so the date itself has to be unambiguous: exactly one address.
  if (location === "" || /^(home|away)$/i.test(location)) {
    return byAddress.size === 1 ? pick([...byAddress.values()][0]) : undefined;
  }

  // A named location must be recognisable in the feed's venue name before its
  // address goes on the page.
  for (const group of byAddress.values()) {
    const match = [...group.venues.values()].find((entry) =>
      namesAgree(location, entry.venue.venue),
    );
    if (match) return match.venue;
  }
  return undefined;
}

/**
 * A result posted by the feed that the curated schedule does not have yet.
 *
 * **Curated always wins**, and this only ever fills a gap. It also refuses to
 * guess: a level gets a result from the feed only when that level played
 * exactly one game on that date, so there is no question which score belongs to
 * which row. A tournament — one curated row, nine feed rows — falls through to
 * whatever a person reconciled, which is where records like "9–0" come from and
 * where they have to keep coming from.
 */
export function feedResultFor(
  match: Pick<Match, "startDate" | "endDate" | "results">,
  level: keyof MatchTimes,
): string | undefined {
  if (!match.startDate || match.endDate) return undefined;
  if (match.results?.[level]?.trim()) return undefined;

  const games = (rankone.levels[level]?.games ?? []).filter(
    (game) => game.date === match.startDate && game.result,
  );
  return games.length === 1 ? games[0].result : undefined;
}

/** The curated result if there is one, otherwise the feed's — see above. */
export function resultFor(
  match: Pick<Match, "startDate" | "endDate" | "results">,
  level: keyof MatchTimes,
): { value: string; fromFeed: boolean } | undefined {
  const curated = match.results?.[level]?.trim();
  if (curated) return { value: curated, fromFeed: false };
  const feed = feedResultFor(match, level);
  return feed ? { value: feed, fromFeed: true } : undefined;
}

/**
 * The feed's own note for a date — "Tournament", "Scrimmage at Legacy
 * volleyball club". Only returned when every level that lists the date agrees,
 * because a note that applies to one level and not another would read on the
 * row as though it applied to all of them.
 */
export function feedNoteFor(match: Pick<Match, "startDate" | "endDate">): string | undefined {
  if (!match.startDate) return undefined;
  const notes = new Set(
    gamesBetween(match.startDate, match.endDate ?? match.startDate)
      .map((game) => game.note.trim())
      .filter(Boolean),
  );
  return notes.size === 1 ? [...notes][0] : undefined;
}
